# .github/workflows/build.yml
name: SonarQube

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    name: Build & SonarCloud
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout sorgenti con history completa (serve a Sonar)
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0          # SonarCloud necessita del blame completo

      # 2) Dipendenze di sistema C/C++, Python, Node, .NET, Ruby
      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential cmake libboost-all-dev libssl-dev \
            python3 python3-pip ruby-full nodejs npm \
            dotnet-sdk-8.0                               # .NET 8 per Avro C#

      # 3) Setup dei JDK (8 facoltativo, 11-17-21 obbligatori; 24 nightly)
      - name: Setup JDK 8 11 17 21 24
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: |
            8
            11
            17
            21
            24

      # 4) Genera il file toolchains.xml per Maven (11-17-21)
      - name: Write toolchains.xml
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/toolchains.xml <<'EOF'
          <toolchains>
            <toolchain>
              <type>jdk</type><provides><version>11</version></provides>
              <configuration><jdkHome>${JAVA_HOME_11_X64}</jdkHome></configuration>
            </toolchain>
            <toolchain>
              <type>jdk</type><provides><version>17</version></provides>
              <configuration><jdkHome>${JAVA_HOME_17_X64}</jdkHome></configuration>
            </toolchain>
            <toolchain>
              <type>jdk</type><provides><version>21</version></provides>
              <configuration><jdkHome>${JAVA_HOME_21_X64}</jdkHome></configuration>
            </toolchain>
          </toolchains>
          EOF

      # 5) Cache del repository Maven
      - name: Cache Maven repo
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      # 6) Build di tutti i moduli + analisi SonarCloud
      - name: Build everything & run SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B -e -X -ntp clean install \
              -Drat.skip=true \
              -Dmaven.build.cache.enabled=false \
              -Dsurefire.rerunFailingTestsCount=2 \
              -Dinvoker.skip=true \
              org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
              -Dsonar.projectKey=StitchMl_avro \
              -Dsonar.login=$SONAR_TOKEN
