# .github/workflows/sonar-gradle.yml
name: SonarCloud (Gradle)
on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17           # Avro richiede JDK ≥17 per il plugin Java
      - name: Cache Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build & Sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew build sonarqube \
             -Dsonar.login=$SONAR_TOKEN \
             -x test                 # se vuoi escludere i test per velocità
